In [1]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [11]:
z = torch.mul(x,x) + torch.mm(x,y) ** 2
print(z.sum())

tensor(148., grad_fn=<SumBackward0>)


In [10]:
out = z.mean()
out.requires_grad
# out.requires_grad_(False)

True

In [13]:
# 现在开始进行反向传播，因为 out 是一个标量，因此 out.backward() 和 out.backward(torch.tensor(1.)) 等价。
out.backward()

In [15]:
x.grad

tensor([[24.5000, 24.5000],
        [24.5000, 24.5000]])

In [16]:
# 雅可比向量例子
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1231.4796,  634.2777, 1117.2234], grad_fn=<MulBackward0>)


In [17]:
# 在这种情况下，y 不再是标量。torch.autograd
#不能直接计算完整的雅可比矩阵，但是如果我们只想要雅可比向量积，只需将这个向量作为参数传给 backward：
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [18]:
# 也可以通过将代码块包装在 with torch.no_grad(): 中，来阻止autograd跟踪设置了 .requires_grad=True 的张量的历史记录。
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
